# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

# Spring Boot
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/example?autoReconnect=true&useSSL=false
    username: root
    password: Abcd1234
    schema: classpath:sql/schema.sql
    schemaUsername: ${spring.datasource.username}
    schemaPassword: ${spring.datasource.password}
    initialization-mode: ALWAYS
    continue-on-error: true

# Camel Spring Boot
camel:
  springboot:
    name: NpaSvc

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel: DEBUG
    org.apache.camel.examples: DEBUG
